### ISSUE TITLE
Language configuration for differents components

### ISSUE THREAD

**Issue by guillemest** [ssuperczynski/ngx-easy-table#214] opened 2019-02-15 13:57 UTC
Hello is possible to add some class or provider in which we can overwrite the labels text in another language, let's say for the global search in the table, or the table footer and so on?

Thanks

**Comment by ssuperczynski** [comment] 2019-02-15 16:06
Hey, this feature will be available soon with 9.0 version.

**Comment by ssuperczynski** [comment] 2019-02-24 12:30
This feature has been implemented partially. You can now define your owe Global Search using Tables API - https://github.com/ssuperczynski/ngx-easy-table/releases/tag/9.0
More of the API configurations will be available in version 10.0

**Comment by guillemest** [comment] 2019-02-25 14:31
Hello thanks for taking my request so quick. Today I updated and I found a couple of issues, in order to use the events and the API. When I import them I get this error for the API: "Error: Can't resolve 'ngx-easy-table/lib'" and for the base component:  Error: Can't resolve 'ngx-easy-table/lib/components/base/base.component'. Can you please check that? Thanks

**Comment by ssuperczynski** [comment] 2019-02-25 15:23
Hey, could you try to `rm -rm node_modules && npm install` first. If it doesn't work, could you add here small component reproduction (with imports) I can't reproduce it on 3 environments.

**Comment by guillemest** [comment] 2019-02-25 16:06
Already try that at first even with rm -rm node_modules && npm cache clear --force && npm install. 

I have created a Stackblitz: [https://stackblitz.com/edit/angular-qvaxxr](url) installed the version 9, I copied your example of global search I just change the exports from:

`import { API } from '../../../../projects/ngx-easy-table/src/lib';`
`import { BaseComponent } from '../../../../projects/ngx-easy-table/src/lib/components/base/base.component';`

to:
`import { API } from 'ngx-easy-table/lib';`
`import { BaseComponent } from 'ngx-easy-table/lib/components/base/base.component';`

and I get an error: **"Can't find package:ngx-easy-table"**

Now check the comment on the line 17 in the **app.components.ts** and see the result.

**Comment by ssuperczynski** [comment] 2019-02-25 16:38
Thanks for the Stackblitz, I'll try to fix it tonight

**Comment by ssuperczynski** [comment] 2019-02-26 08:38
Fixed, and released as 9.0.1. Please refer to https://ngx-easy-table.eu/#/api-doc for the changes 🙂

**Closed** 2019-03-05 06:41 UTC
